name: Clanker Report
description: Post reports made from LLMs analysis
labels: ["clanker"]
body:
  - type: textarea
    id: report
    attributes:
      label: What does the AI say?
      description: |
        Describe what was prompted and the result
      placeholder: Paste here the reported problem
    validations:
      required: true